import axios from 'axios';

export const MODEL_URL = 'http://nlpsgf-env.a3pandx5ib.us-east-2.elasticbeanstalk.com/';
export const DEV_URL = 'http://127.0.0.1:5000/'
export const PROD_URL = 'https://nlpsgf-env.a3pandx5ib.us-east-2.elasticbeanstalk.com/'

// function checkStatus(res) {
//   if (!res.ok) {
//     throw new Error(res.statusText);
//   }
//   return res.json();
// }

// export default function fetchGroups() {
//   return axios.get(`${MODEL_URL}`)
//     .then(checkStatus)
//     .then(res => res.json())
//     .then(json => console.log(json))
// }


export default function fetchGroups() {
    axios.get(MODEL_URL)
    .then(response => response.json())
    .then(json => console.log(json))
  }




export const group_url = {'offmychest': 'https://www.reddit.com/r/offmychest/',
 'add': 'https://www.reddit.com/r/add/',
 'cripplingalcoholism': 'https://www.reddit.com/r/cripplingalcoholism/',
 'disorder': 'https://www.reddit.com/r/disorder/',
 'Health': 'https://www.reddit.com/r/Health/',
 'HelathProject': 'https://www.reddit.com/r/HelathProject/',
 'leaves': 'https://www.reddit.com/r/leaves/',
 'MenGetRapedToo': 'https://www.reddit.com/r/MenGetRapedToo/',
 'rapecounseling': 'https://www.reddit.com/r/rapecounseling/',
 'CupsofTea': 'https://www.reddit.com/r/CupsofTea/',
 'addiction': 'https://www.reddit.com/r/addiction/',
 'ADHD': 'https://www.reddit.com/r/ADHD/',
 'Advice': 'https://www.reddit.com/r/Advice/',
 'affirmations': 'https://www.reddit.com/r/affirmations/',
 'afterthesilence': 'https://www.reddit.com/r/afterthesilence/',
 'Agoraphobia': 'https://www.reddit.com/r/Agoraphobia/',
 'AlAnon': 'https://www.reddit.com/r/AlAnon/',
 'alcoholicsanonymous': 'https://www.reddit.com/r/alcoholicsanonymous/',
 'alcoholism': 'https://www.reddit.com/r/alcoholism/',
 'Anger': 'https://www.reddit.com/r/Anger/',
 'Antipsychiatry': 'https://www.reddit.com/r/Antipsychiatry/',
 'Anxiety': 'https://www.reddit.com/r/Anxiety/',
 'Anxietyhelp': 'https://www.reddit.com/r/Anxietyhelp/',
 'anxietysuccess': 'https://www.reddit.com/r/anxietysuccess/',
 'anxietysupporters': 'https://www.reddit.com/r/anxietysupporters/',
 'AskDocs': 'https://www.reddit.com/r/AskDocs/',
 'aspergers': 'https://www.reddit.com/r/aspergers/',
 'AspiePartners': 'https://www.reddit.com/r/AspiePartners/',
 'AtheistTwelveSteppers': 'https://www.reddit.com/r/AtheistTwelveSteppers/',
 'behavior': 'https://www.reddit.com/r/behavior/',
 'behaviortherapy': 'https://www.reddit.com/r/behaviortherapy/',
 'bingeeating': 'https://www.reddit.com/r/bingeeating/',
 'BipolarReddit': 'https://www.reddit.com/r/BipolarReddit/',
 'BipolaSOs': 'https://www.reddit.com/r/BipolaSOs/',
 'BodyAcceptance': 'https://www.reddit.com/r/BodyAcceptance/',
 'BPD': 'https://www.reddit.com/r/BPD/',
 'bulimia': 'https://www.reddit.com/r/bulimia/',
 'CompulsiveSkinPicking': 'https://www.reddit.com/r/CompulsiveSkinPicking/',
 'dbtselfhelp': 'https://www.reddit.com/r/dbtselfhelp/',
 'depression': 'https://www.reddit.com/r/depression/',
 'depressionregimens': 'https://www.reddit.com/r/depressionregimens/',
 'disability': 'https://www.reddit.com/r/disability/',
 'distractit': 'https://www.reddit.com/r/distractit/',
 'domesticviolence': 'https://www.reddit.com/r/domesticviolence/',
 'downsyndrome': 'https://www.reddit.com/r/downsyndrome/',
 'DysmorphicDisorder': 'https://www.reddit.com/r/DysmorphicDisorder/',
 'eating_disorders': 'https://www.reddit.com/r/eating_disorders/',
 'EastingDisorderHope': 'https://www.reddit.com/r/EastingDisorderHope/',
 'EatingDisorders': 'https://www.reddit.com/r/EatingDisorders/',
 'emetophobia': 'https://www.reddit.com/r/emetophobia/',
 'EOOD': 'https://www.reddit.com/r/EOOD/',
 'ForeverAlone': 'https://www.reddit.com/r/ForeverAlone/',
 'fuckeatingdisorders': 'https://www.reddit.com/r/fuckeatingdisorders/',
 'GetMotivated': 'https://www.reddit.com/r/GetMotivated/',
 'getting_over_it': 'https://www.reddit.com/r/getting_over_it/',
 'GFD': 'https://www.reddit.com/r/GFD/',
 'HaveHope': 'https://www.reddit.com/r/HaveHope/',
 'HealthAnxiety': 'https://www.reddit.com/r/HealthAnxiety/',
 'helpmecope': 'https://www.reddit.com/r/helpmecope/',
 'itgetsbetter': 'https://www.reddit.com/r/itgetsbetter/',
 'mentalhealth': 'https://www.reddit.com/r/mentalhealth/',
 'mentalillness': 'https://www.reddit.com/r/mentalillness/',
 'mentalpod': 'https://www.reddit.com/r/mentalpod/',
 'mixednuts': 'https://www.reddit.com/r/mixednuts/',
 'MMFB': 'https://www.reddit.com/r/MMFB/',
 'MSTsurvivors': 'https://www.reddit.com/r/MSTsurvivors/',
 'needadvice': 'https://www.reddit.com/r/needadvice/',
 'Needafriend': 'https://www.reddit.com/r/Needafriend/',
 'neurodiversity': 'https://www.reddit.com/r/neurodiversity/',
 'NoFap': 'https://www.reddit.com/r/NoFap/',
 'nosurf': 'https://www.reddit.com/r/nosurf/',
 'OCD': 'https://www.reddit.com/r/OCD/',
 'OCPD': 'https://www.reddit.com/r/OCPD/',
 'OpiatesRecovery': 'https://www.reddit.com/r/OpiatesRecovery/',
 'PanicParty': 'https://www.reddit.com/r/PanicParty/',
 'Phobia': 'https://www.reddit.com/r/Phobia/',
 'PsychiatricFreedom': 'https://www.reddit.com/r/PsychiatricFreedom/',
 'Psychiatry': 'https://www.reddit.com/r/Psychiatry/',
 'psychology': 'https://www.reddit.com/r/psychology/',
 'psychopathology': 'https://www.reddit.com/r/psychopathology/',
 'psychotherapy': 'https://www.reddit.com/r/psychotherapy/',
 'psychotic_features': 'https://www.reddit.com/r/psychotic_features/',
 'psychoticreddit': 'https://www.reddit.com/r/psychoticreddit/',
 'ptsd': 'https://www.reddit.com/r/ptsd/',
 'quittingkratom': 'https://www.reddit.com/r/quittingkratom/',
 'rape': 'https://www.reddit.com/r/rape/',
 'reasonstolive': 'https://www.reddit.com/r/reasonstolive/',
 'rehabtherapy': 'https://www.reddit.com/r/rehabtherapy/',
 'sad': 'https://www.reddit.com/r/sad/',
 'schizoaffective': 'https://www.reddit.com/r/schizoaffective/',
 'schizophrenia': 'https://www.reddit.com/r/schizophrenia/',
 'secondary_survivors': 'https://www.reddit.com/r/secondary_survivors/',
 'selfharm': 'https://www.reddit.com/r/selfharm/',
 'SelfHarmCommunity': 'https://www.reddit.com/r/SelfHarmCommunity/',
 'selfhelp': 'https://www.reddit.com/r/selfhelp/',
 'siblingsupport': 'https://www.reddit.com/r/siblingsupport/',
 'slp': 'https://www.reddit.com/r/slp/',
 'SMARTRecovery': 'https://www.reddit.com/r/SMARTRecovery/',
 'socialanxiety': 'https://www.reddit.com/r/socialanxiety/',
 'socialskills': 'https://www.reddit.com/r/socialskills/',
 'socialwork': 'https://www.reddit.com/r/socialwork/',
 'socialworkresources': 'https://www.reddit.com/r/socialworkresources/',
 'speciaed': 'https://www.reddit.com/r/speciaed/',
 'StopDipping': 'https://www.reddit.com/r/StopDipping/',
 'stopdrinking': 'https://www.reddit.com/r/stopdrinking/',
 'stopgaming': 'https://www.reddit.com/r/stopgaming/',
 'StopSelfHarm': 'https://www.reddit.com/r/StopSelfHarm/',
 'stopsmoking': 'https://www.reddit.com/r/stopsmoking/',
 'SuicideWatch': 'https://www.reddit.com/r/SuicideWatch/',
 'survivorsofabuse': 'https://www.reddit.com/r/survivorsofabuse/',
 'swami': 'https://www.reddit.com/r/swami/',
 'Teetotal': 'https://www.reddit.com/r/Teetotal/',
 'TheMixedNuts': 'https://www.reddit.com/r/TheMixedNuts/',
 'tOCD': 'https://www.reddit.com/r/tOCD/',
 'Tourettes': 'https://www.reddit.com/r/Tourettes/',
 'traumatoolbox': 'https://www.reddit.com/r/traumatoolbox/',
 'Trichsters': 'https://www.reddit.com/r/Trichsters/',
 'TwoXADHD': 'https://www.reddit.com/r/TwoXADHD/',
 'uniqueminds': 'https://www.reddit.com/r/uniqueminds/',
 'whatsbotheringyou': 'https://www.reddit.com/r/whatsbotheringyou/'}


const subreddits_mental_illness = [
    'offmychest',
    'add',
    'cripplingalcoholism',
    'disorder',
    'Health',
    'HelathProject',
    'leaves',
    'MenGetRapedToo',
    'rapecounseling',
    'CupsofTea',
    'addiction',
    'ADHD',
    'Advice',
    'affirmations',
    'afterthesilence',
    'Agoraphobia',
    'AlAnon',
    'alcoholicsanonymous',
    'alcoholism',
    'Anger',
    'Antipsychiatry',
    'Anxiety',
    'Anxietyhelp',
    'anxietysuccess',
    'anxietysupporters',
    'AskDocs',
    'aspergers',
    'AspiePartners',
    'AtheistTwelveSteppers',
    'behavior',
    'behaviortherapy',
    'bingeeating',
    'BipolarReddit',
    'BipolaSOs',
    'BodyAcceptance',
    'BPD',
    'bulimia',
    'CompulsiveSkinPicking',
    'dbtselfhelp',
    'depression',
    'depressionregimens',
    'disability',
    'distractit',
    'domesticviolence',
    'downsyndrome',
    'DysmorphicDisorder',
    'eating_disorders',
    'EastingDisorderHope',
    'EatingDisorders',
    'emetophobia',
    'EOOD',
    'ForeverAlone',
    'fuckeatingdisorders',
    'GetMotivated',
    'getting_over_it',
    'GFD',
    'HaveHope',
    'HealthAnxiety',
    'helpmecope',
    'itgetsbetter',
    'leaves',
    'mentalhealth',
    'mentalillness',
    'mentalpod',
    'mixednuts',
    'MMFB',
    'MSTsurvivors',
    'needadvice',
    'Needafriend',
    'neurodiversity',
    'NoFap',
    'nosurf',
    'OCD',
    'OCPD',
    'OpiatesRecovery',
    'PanicParty',
    'Phobia',
    'PsychiatricFreedom',
    'Psychiatry',
    'psychology',
    'psychopathology',
    'psychotherapy',
    'psychotic_features',
    'psychoticreddit',
    'ptsd',
    'quittingkratom',
    'rape',
    'rapecounseling',
    'reasonstolive',
    'rehabtherapy',
    'sad',
    'schizoaffective',
    'schizophrenia',
    'secondary_survivors',
    'selfharm',
    'SelfHarmCommunity',
    'selfhelp',
    'siblingsupport',
    'slp',
    'SMARTRecovery',
    'socialanxiety',
    'socialskills',
    'socialwork',
    'socialworkresources',
    'speciaed',
    'StopDipping',
    'stopdrinking',
    'stopgaming',
    'StopSelfHarm',
    'stopsmoking',
    'SuicideWatch',
    'survivorsofabuse',
    'swami',
    'Teetotal',
    'TheMixedNuts',
    'tOCD',
    'Tourettes',
    'traumatoolbox',
    'Trichsters',
    'TwoXADHD',
    'uniqueminds',
    'whatsbotheringyou'
]





